version: '3.9'
services:
  app-go:
    container_name: golang_app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=go_database
      - DB_HOST=postgresdb
      - DATABASE_PORT=5432
      - TITLE=go_database
      - VERSION=0.0.0
      - DESCRIPTION=go database by cristian bustamante

    depends_on:
      - postgresdb
    networks:
      - golang_network

  postgresdb:
    image: postgresdb
    build:
      context: ../database
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - golang_network

volumes:
  pg_data:
    external: true

networks:
  golang_network:
    external: true